### ISSUE TITLE
Fetching codelocations with API token does not return same results

### ISSUE THREAD

**Issue by skiyooka** [blackducksoftware/sage#10]
User has roles Global Code Scanner, Super User and, System Administrator

Observed behavior: when using an API token and hitting /api/codelocations returned results do not include "projectName", "versionName" (assuming mapped) and "status". When using username/password credentials, returned results do include these elements.

Expected behavior: /api/codelocations should return same results regardless of using API token or username/password credentials.

Observed in 2020.10 and 2020.12

**Comment by gsnyder2007** [comment]
Yeah, wonder if the role shouldn't be Global Project Viewer instead?

**Comment by skiyooka** [comment]
This is related to the default Content-type if not specified. Given the following 2 possibilities in the headers:
- application/vnd.blackducksoftware.internal-1+json
- application/vnd.blackducksoftware.scan-4+json

Assuming Content-type is not specified...
- If username/password is used, it defaults to internal-1+json Content-type which returns extra information: "projectName", "versionName", and "status".
- Conversely if a user access token is used, it defaults to the scan-4+json Content-type which does not include those elements.

So the lesson learned, like HUB-28089, is to always specify the Content-type otherwise you may end up using the internal (and unsupported) one by accident.

**Comment by skiyooka** [comment]
Explicitly specifying the 'accept' and 'content-type' headers gives consistent results regardless of username/password versus token authentication.
