### ISSUE TITLE
Needs debug option.

### ISSUE THREAD

**Issue by sig-piskule** [blackducksoftware/sage#3]
This needs a debug option.

If a customer provides us with a key, and the key is invalid, we get a stack trace that is impossible to debug. This is because the result for a 401 does not respond with a JSON object, and the libraries are expecting a JSON object. Sage tries to use the JSON decoder to decode a null object, and this fails.

Knowing that the original HTTP Response was 401 would be extremely helpful. I won't need to manually modify python libraries to determine why a customer key is not working.

**Comment by skiyooka** [comment]
Upon investigation, this is better handled within hub-rest-api-python during the HTTP POST to Hub for authentication. I'll work something into there in conjunction with bearer_token expiry handling.
