### ISSUE TITLE
Add Error Handling to Sage

### ISSUE THREAD

**Issue by adawalli** [blackducksoftware/sage#30]
The sage tool is really useful (and often asked to be run by support when DB issues arise). We have run into a few issues with sage where the state of hub may be different at the end of a run compared to the beginning (e.g., projects and/or project versions may be deleted by the time sage goes to pull information later on) - this causes sage to crash, even several hours into a run (and before anything is written to disk)

The request is to add some error handling so that sage can proceed even when state has changed throughout the run.

**Comment by gsnyder2007** [comment]
@adawalli sorry for the delayed response. Any suggestions for where the error handling might be needed? I can analyze and probably guess but if I had a stack trace or more information about where in the code the problem is occurring the chances of a successful fix are, um, greatly increased. :-)

**Comment by gsnyder2007** [comment]
Nevermind, I found the additional details elsewhere. I've got what I need and will attempt a fix shortly.

**Comment by adawalli** [comment]
Thanks!

**Comment by gsnyder2007** [comment]
I've pushed a branch (30-add-error-handling-to-sage) that I believe fixes the issue. Would be great if I could get someone to test. I did a manual test where I put a breakpoint in, then deleted a project, and then let things continue to simulate the condition that caused the original error. But, again, would be good to get some more tests done to make sure the fix does the job.

**Comment by gsnyder2007** [comment]
@adawalli were you able to complete the testing? If so, could you post the results? I'm holding off merging the fix until I see that someone has confirmed I didn't break something.

**Comment by svcsectool** [comment]
I am testing it out right this moment - thanks for the reminder!

**Comment by adawalli** [comment]
I am testing it out right now, thanks for the reminder!

**Comment by adawalli** [comment]
This works great, thanks!
